// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: answers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnswer = `-- name: CreateAnswer :one
INSERT INTO answers (question_id, sort_order, text, is_correct)
VALUES ($1, $2, $3, $4)
RETURNING id, question_id, sort_order, text, is_correct
`

type CreateAnswerParams struct {
	QuestionID pgtype.UUID `json:"question_id"`
	SortOrder  int32       `json:"sort_order"`
	Text       string      `json:"text"`
	IsCorrect  bool        `json:"is_correct"`
}

func (q *Queries) CreateAnswer(ctx context.Context, arg CreateAnswerParams) (Answer, error) {
	row := q.db.QueryRow(ctx, createAnswer,
		arg.QuestionID,
		arg.SortOrder,
		arg.Text,
		arg.IsCorrect,
	)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.SortOrder,
		&i.Text,
		&i.IsCorrect,
	)
	return i, err
}

const getAnswersByQuestionID = `-- name: GetAnswersByQuestionID :many
SELECT id, question_id, sort_order, text, is_correct FROM answers WHERE question_id = $1 ORDER BY sort_order
`

func (q *Queries) GetAnswersByQuestionID(ctx context.Context, questionID pgtype.UUID) ([]Answer, error) {
	rows, err := q.db.Query(ctx, getAnswersByQuestionID, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Answer{}
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.SortOrder,
			&i.Text,
			&i.IsCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnswersByQuestionIDs = `-- name: GetAnswersByQuestionIDs :many
SELECT id, question_id, sort_order, text, is_correct FROM answers WHERE question_id = ANY($1::uuid[]) ORDER BY question_id, sort_order
`

func (q *Queries) GetAnswersByQuestionIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Answer, error) {
	rows, err := q.db.Query(ctx, getAnswersByQuestionIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Answer{}
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.SortOrder,
			&i.Text,
			&i.IsCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
