// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING token, user_id, expires_at, created_at
`

type CreateSessionParams struct {
	Token     string             `json:"token"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createVerificationCode = `-- name: CreateVerificationCode :one
INSERT INTO verification_codes (user_id, code, purpose, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, code, purpose, expires_at, used_at, created_at
`

type CreateVerificationCodeParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Code      string             `json:"code"`
	Purpose   string             `json:"purpose"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, createVerificationCode,
		arg.UserID,
		arg.Code,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const getLatestVerificationCode = `-- name: GetLatestVerificationCode :one
SELECT id, user_id, code, purpose, expires_at, used_at, created_at FROM verification_codes
WHERE user_id = $1 AND purpose = $2 AND used_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestVerificationCodeParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Purpose string      `json:"purpose"`
}

func (q *Queries) GetLatestVerificationCode(ctx context.Context, arg GetLatestVerificationCodeParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, getLatestVerificationCode, arg.UserID, arg.Purpose)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT token, user_id, expires_at, created_at FROM sessions WHERE token = $1 AND expires_at > now()
`

func (q *Queries) GetSession(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, token)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidatePreviousCodes = `-- name: InvalidatePreviousCodes :exec
UPDATE verification_codes
SET used_at = now()
WHERE user_id = $1 AND purpose = $2 AND used_at IS NULL
`

type InvalidatePreviousCodesParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Purpose string      `json:"purpose"`
}

func (q *Queries) InvalidatePreviousCodes(ctx context.Context, arg InvalidatePreviousCodesParams) error {
	_, err := q.db.Exec(ctx, invalidatePreviousCodes, arg.UserID, arg.Purpose)
	return err
}

const markCodeUsed = `-- name: MarkCodeUsed :exec
UPDATE verification_codes SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkCodeUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markCodeUsed, id)
	return err
}
