// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Answer struct {
	ID         pgtype.UUID `json:"id"`
	QuestionID pgtype.UUID `json:"question_id"`
	SortOrder  int32       `json:"sort_order"`
	Text       string      `json:"text"`
	IsCorrect  bool        `json:"is_correct"`
}

type GameResult struct {
	ID             pgtype.UUID        `json:"id"`
	RoomID         pgtype.UUID        `json:"room_id"`
	PlayerID       pgtype.UUID        `json:"player_id"`
	Score          int32              `json:"score"`
	CorrectAnswers int32              `json:"correct_answers"`
	TotalQuestions int32              `json:"total_questions"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
}

type Player struct {
	ID      pgtype.UUID `json:"id"`
	RoomID  pgtype.UUID `json:"room_id"`
	Name    string      `json:"name"`
	IsReady bool        `json:"is_ready"`
	Score   int32       `json:"score"`
}

type Question struct {
	ID        pgtype.UUID `json:"id"`
	QuizID    pgtype.UUID `json:"quiz_id"`
	SortOrder int32       `json:"sort_order"`
	Text      string      `json:"text"`
}

type Quiz struct {
	ID              pgtype.UUID        `json:"id"`
	Code            string             `json:"code"`
	Name            string             `json:"name"`
	Difficulty      string             `json:"difficulty"`
	QuestionsCount  int32              `json:"questions_count"`
	TimePerQuestion int32              `json:"time_per_question"`
	IsPublic        bool               `json:"is_public"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Room struct {
	ID              pgtype.UUID        `json:"id"`
	Code            string             `json:"code"`
	QuizID          pgtype.UUID        `json:"quiz_id"`
	HostPlayerID    pgtype.UUID        `json:"host_player_id"`
	Status          string             `json:"status"`
	CurrentQuestion int32              `json:"current_question"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}
