// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (room_id, name, is_ready, score)
VALUES ($1, $2, $3, $4)
RETURNING id, room_id, name, is_ready, score
`

type CreatePlayerParams struct {
	RoomID  pgtype.UUID `json:"room_id"`
	Name    string      `json:"name"`
	IsReady bool        `json:"is_ready"`
	Score   int32       `json:"score"`
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, createPlayer,
		arg.RoomID,
		arg.Name,
		arg.IsReady,
		arg.Score,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Name,
		&i.IsReady,
		&i.Score,
	)
	return i, err
}

const deletePlayer = `-- name: DeletePlayer :exec
DELETE FROM players WHERE id = $1
`

func (q *Queries) DeletePlayer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePlayer, id)
	return err
}

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT id, room_id, name, is_ready, score FROM players WHERE id = $1
`

func (q *Queries) GetPlayerByID(ctx context.Context, id pgtype.UUID) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByID, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Name,
		&i.IsReady,
		&i.Score,
	)
	return i, err
}

const getPlayersByRoomID = `-- name: GetPlayersByRoomID :many
SELECT id, room_id, name, is_ready, score FROM players WHERE room_id = $1
`

func (q *Queries) GetPlayersByRoomID(ctx context.Context, roomID pgtype.UUID) ([]Player, error) {
	rows, err := q.db.Query(ctx, getPlayersByRoomID, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Player{}
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Name,
			&i.IsReady,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayerReady = `-- name: UpdatePlayerReady :one
UPDATE players SET is_ready = $2 WHERE id = $1
RETURNING id, room_id, name, is_ready, score
`

type UpdatePlayerReadyParams struct {
	ID      pgtype.UUID `json:"id"`
	IsReady bool        `json:"is_ready"`
}

func (q *Queries) UpdatePlayerReady(ctx context.Context, arg UpdatePlayerReadyParams) (Player, error) {
	row := q.db.QueryRow(ctx, updatePlayerReady, arg.ID, arg.IsReady)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Name,
		&i.IsReady,
		&i.Score,
	)
	return i, err
}

const updatePlayerScore = `-- name: UpdatePlayerScore :one
UPDATE players SET score = $2 WHERE id = $1
RETURNING id, room_id, name, is_ready, score
`

type UpdatePlayerScoreParams struct {
	ID    pgtype.UUID `json:"id"`
	Score int32       `json:"score"`
}

func (q *Queries) UpdatePlayerScore(ctx context.Context, arg UpdatePlayerScoreParams) (Player, error) {
	row := q.db.QueryRow(ctx, updatePlayerScore, arg.ID, arg.Score)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Name,
		&i.IsReady,
		&i.Score,
	)
	return i, err
}
