// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: questions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (quiz_id, sort_order, text)
VALUES ($1, $2, $3)
RETURNING id, quiz_id, sort_order, text
`

type CreateQuestionParams struct {
	QuizID    pgtype.UUID `json:"quiz_id"`
	SortOrder int32       `json:"sort_order"`
	Text      string      `json:"text"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion, arg.QuizID, arg.SortOrder, arg.Text)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.SortOrder,
		&i.Text,
	)
	return i, err
}

const deleteQuestionsByQuizID = `-- name: DeleteQuestionsByQuizID :exec
DELETE FROM questions WHERE quiz_id = $1
`

func (q *Queries) DeleteQuestionsByQuizID(ctx context.Context, quizID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuestionsByQuizID, quizID)
	return err
}

const getQuestionsByQuizID = `-- name: GetQuestionsByQuizID :many
SELECT id, quiz_id, sort_order, text FROM questions WHERE quiz_id = $1 ORDER BY sort_order
`

func (q *Queries) GetQuestionsByQuizID(ctx context.Context, quizID pgtype.UUID) ([]Question, error) {
	rows, err := q.db.Query(ctx, getQuestionsByQuizID, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.SortOrder,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
