// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quizzes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuiz = `-- name: CreateQuiz :one
INSERT INTO quizzes (code, name, difficulty, questions_count, time_per_question, is_public)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, code, name, difficulty, questions_count, time_per_question, is_public, created_at
`

type CreateQuizParams struct {
	Code            string `json:"code"`
	Name            string `json:"name"`
	Difficulty      string `json:"difficulty"`
	QuestionsCount  int32  `json:"questions_count"`
	TimePerQuestion int32  `json:"time_per_question"`
	IsPublic        bool   `json:"is_public"`
}

func (q *Queries) CreateQuiz(ctx context.Context, arg CreateQuizParams) (Quiz, error) {
	row := q.db.QueryRow(ctx, createQuiz,
		arg.Code,
		arg.Name,
		arg.Difficulty,
		arg.QuestionsCount,
		arg.TimePerQuestion,
		arg.IsPublic,
	)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Difficulty,
		&i.QuestionsCount,
		&i.TimePerQuestion,
		&i.IsPublic,
		&i.CreatedAt,
	)
	return i, err
}

const deleteQuiz = `-- name: DeleteQuiz :exec
DELETE FROM quizzes WHERE id = $1
`

func (q *Queries) DeleteQuiz(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuiz, id)
	return err
}

const getQuizByCode = `-- name: GetQuizByCode :one
SELECT id, code, name, difficulty, questions_count, time_per_question, is_public, created_at FROM quizzes WHERE code = $1
`

func (q *Queries) GetQuizByCode(ctx context.Context, code string) (Quiz, error) {
	row := q.db.QueryRow(ctx, getQuizByCode, code)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Difficulty,
		&i.QuestionsCount,
		&i.TimePerQuestion,
		&i.IsPublic,
		&i.CreatedAt,
	)
	return i, err
}

const getQuizByID = `-- name: GetQuizByID :one
SELECT id, code, name, difficulty, questions_count, time_per_question, is_public, created_at FROM quizzes WHERE id = $1
`

func (q *Queries) GetQuizByID(ctx context.Context, id pgtype.UUID) (Quiz, error) {
	row := q.db.QueryRow(ctx, getQuizByID, id)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Difficulty,
		&i.QuestionsCount,
		&i.TimePerQuestion,
		&i.IsPublic,
		&i.CreatedAt,
	)
	return i, err
}

const listPublicQuizzes = `-- name: ListPublicQuizzes :many
SELECT id, code, name, difficulty, questions_count, time_per_question, is_public, created_at FROM quizzes WHERE is_public = true ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListPublicQuizzesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPublicQuizzes(ctx context.Context, arg ListPublicQuizzesParams) ([]Quiz, error) {
	rows, err := q.db.Query(ctx, listPublicQuizzes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quiz{}
	for rows.Next() {
		var i Quiz
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Difficulty,
			&i.QuestionsCount,
			&i.TimePerQuestion,
			&i.IsPublic,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
