// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (code, quiz_id, host_player_id, status)
VALUES ($1, $2, $3, $4)
RETURNING id, code, quiz_id, host_player_id, status, current_question, created_at
`

type CreateRoomParams struct {
	Code         string      `json:"code"`
	QuizID       pgtype.UUID `json:"quiz_id"`
	HostPlayerID pgtype.UUID `json:"host_player_id"`
	Status       string      `json:"status"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.Code,
		arg.QuizID,
		arg.HostPlayerID,
		arg.Status,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.QuizID,
		&i.HostPlayerID,
		&i.Status,
		&i.CurrentQuestion,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms WHERE id = $1
`

func (q *Queries) DeleteRoom(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoom, id)
	return err
}

const getRoomByCode = `-- name: GetRoomByCode :one
SELECT id, code, quiz_id, host_player_id, status, current_question, created_at FROM rooms WHERE code = $1
`

func (q *Queries) GetRoomByCode(ctx context.Context, code string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByCode, code)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.QuizID,
		&i.HostPlayerID,
		&i.Status,
		&i.CurrentQuestion,
		&i.CreatedAt,
	)
	return i, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, code, quiz_id, host_player_id, status, current_question, created_at FROM rooms WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id pgtype.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.QuizID,
		&i.HostPlayerID,
		&i.Status,
		&i.CurrentQuestion,
		&i.CreatedAt,
	)
	return i, err
}

const setRoomHost = `-- name: SetRoomHost :exec
UPDATE rooms SET host_player_id = $2 WHERE id = $1
`

type SetRoomHostParams struct {
	ID           pgtype.UUID `json:"id"`
	HostPlayerID pgtype.UUID `json:"host_player_id"`
}

func (q *Queries) SetRoomHost(ctx context.Context, arg SetRoomHostParams) error {
	_, err := q.db.Exec(ctx, setRoomHost, arg.ID, arg.HostPlayerID)
	return err
}

const updateRoomStatus = `-- name: UpdateRoomStatus :one
UPDATE rooms SET status = $2, current_question = $3 WHERE id = $1
RETURNING id, code, quiz_id, host_player_id, status, current_question, created_at
`

type UpdateRoomStatusParams struct {
	ID              pgtype.UUID `json:"id"`
	Status          string      `json:"status"`
	CurrentQuestion int32       `json:"current_question"`
}

func (q *Queries) UpdateRoomStatus(ctx context.Context, arg UpdateRoomStatusParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoomStatus, arg.ID, arg.Status, arg.CurrentQuestion)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.QuizID,
		&i.HostPlayerID,
		&i.Status,
		&i.CurrentQuestion,
		&i.CreatedAt,
	)
	return i, err
}
