// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, nickname, email, password_hash, vk_id, is_verified, verified_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, nickname, email, password_hash, vk_id, is_verified, verified_at, created_at
`

type CreateUserParams struct {
	Name         string             `json:"name"`
	Nickname     string             `json:"nickname"`
	Email        pgtype.Text        `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	VkID         pgtype.Text        `json:"vk_id"`
	IsVerified   bool               `json:"is_verified"`
	VerifiedAt   pgtype.Timestamptz `json:"verified_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Nickname,
		arg.Email,
		arg.PasswordHash,
		arg.VkID,
		arg.IsVerified,
		arg.VerifiedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Nickname,
		&i.Email,
		&i.PasswordHash,
		&i.VkID,
		&i.IsVerified,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, nickname, email, password_hash, vk_id, is_verified, verified_at, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Nickname,
		&i.Email,
		&i.PasswordHash,
		&i.VkID,
		&i.IsVerified,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, nickname, email, password_hash, vk_id, is_verified, verified_at, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Nickname,
		&i.Email,
		&i.PasswordHash,
		&i.VkID,
		&i.IsVerified,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByNickname = `-- name: GetUserByNickname :one
SELECT id, name, nickname, email, password_hash, vk_id, is_verified, verified_at, created_at FROM users WHERE nickname = $1
`

func (q *Queries) GetUserByNickname(ctx context.Context, nickname string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByNickname, nickname)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Nickname,
		&i.Email,
		&i.PasswordHash,
		&i.VkID,
		&i.IsVerified,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByVKID = `-- name: GetUserByVKID :one
SELECT id, name, nickname, email, password_hash, vk_id, is_verified, verified_at, created_at FROM users WHERE vk_id = $1
`

func (q *Queries) GetUserByVKID(ctx context.Context, vkID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByVKID, vkID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Nickname,
		&i.Email,
		&i.PasswordHash,
		&i.VkID,
		&i.IsVerified,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markUserVerified = `-- name: MarkUserVerified :one
UPDATE users SET is_verified = true, verified_at = now() WHERE id = $1
RETURNING id, name, nickname, email, password_hash, vk_id, is_verified, verified_at, created_at
`

func (q *Queries) MarkUserVerified(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, markUserVerified, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Nickname,
		&i.Email,
		&i.PasswordHash,
		&i.VkID,
		&i.IsVerified,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET name = $2, nickname = $3 WHERE id = $1
RETURNING id, name, nickname, email, password_hash, vk_id, is_verified, verified_at, created_at
`

type UpdateUserParams struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Nickname string      `json:"nickname"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name, arg.Nickname)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Nickname,
		&i.Email,
		&i.PasswordHash,
		&i.VkID,
		&i.IsVerified,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}
